import mongoose from 'mongoose';

/**
 * Solution schema — DATABASE_SCHEMA.md §3
 *
 * Fields:
 *   _id         ObjectId          auto-generated
 *   userId      ObjectId          required — references users._id (DATABASE_SCHEMA.md §4)
 *   title       String            required
 *   problem     String            required
 *   solution    String            required
 *   code        String            optional
 *   technology  String            optional
 *   language    String            optional
 *   tags        [String]          optional array
 *   project     String            optional
 *   notes       String            optional
 *   sourceUrl   String            optional, URL-validated when present
 *   embedding   [Number]          optional — generated by Gemini (Phase 7)
 *                                 768-dimensional per DATABASE_SCHEMA.md §7
 *   createdAt   Date              managed by Mongoose timestamps
 *   updatedAt   Date              managed by Mongoose timestamps
 *
 * Vector Search index on `embedding`:
 *   This index must be created manually in the MongoDB Atlas UI (not via Mongoose).
 *   See AI_SPEC.md and DATABASE_SCHEMA.md §6.
 *   Index type: Vector Search | field: embedding | dimensions: 768 | similarity: cosine
 *   Do NOT create this index until Phase 7 — embedding generation is not implemented yet.
 */
const solutionSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'userId is required'],
      index: true,      // DATABASE_SCHEMA.md §6: index supporting userId-based retrieval
    },

    // ── Required fields ────────────────────────────────────────────────────────
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
    },
    problem: {
      type: String,
      required: [true, 'Problem description is required'],
      trim: true,
    },
    solution: {
      type: String,
      required: [true, 'Solution description is required'],
      trim: true,
    },

    // ── Optional fields ────────────────────────────────────────────────────────
    code: {
      type: String,
      default: undefined,
    },
    technology: {
      type: String,
      trim: true,
      default: undefined,
    },
    language: {
      type: String,
      trim: true,
      default: undefined,
    },
    tags: {
      type: [String],
      default: [],
    },
    project: {
      type: String,
      trim: true,
      default: undefined,
    },
    notes: {
      type: String,
      trim: true,
      default: undefined,
    },

    // ── sourceUrl — validated when present (DATABASE_SCHEMA.md §9) ─────────────
    sourceUrl: {
      type: String,
      trim: true,
      default: undefined,
      validate: {
        validator: function (v) {
          if (!v) return true; // field is optional
          return /^https?:\/\/.+/.test(v);
        },
        message: 'sourceUrl must be a valid http or https URL',
      },
    },

    // ── AI embedding — populated by Gemini service (Phase 7) ──────────────────
    // 768-dimensional vector. Optional until successfully generated.
    // The MongoDB Atlas Vector Search index on this field must be created
    // manually in the Atlas UI — it cannot be expressed in a Mongoose schema.
    embedding: {
      type: [Number],
      default: undefined, // field is absent from document until embedding is generated
      select: false,       // exclude from query results by default to avoid sending
    },                     // large vectors to the client unnecessarily
  },
  {
    timestamps: true, // adds createdAt and updatedAt — DATABASE_SCHEMA.md §3
  }
);

const Solution = mongoose.model('Solution', solutionSchema);

export default Solution;
