import mongoose from 'mongoose';

/**
 * User schema — DATABASE_SCHEMA.md §2
 *
 * Fields:
 *   _id          ObjectId       auto-generated by MongoDB
 *   name         String         required
 *   email        String         required, unique, lowercase-normalised
 *   passwordHash String         required  (never store plaintext — PROJECT_RULES.md §5)
 *   createdAt    Date           set on creation only
 *
 * Note: updatedAt is intentionally omitted for User; the schema only
 * specifies createdAt (DATABASE_SCHEMA.md §2).
 */
const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true,
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,       // creates the unique index required by DATABASE_SCHEMA.md §6
    lowercase: true,    // normalisation — stores and queries in lowercase
    trim: true,
  },
  passwordHash: {
    type: String,
    required: [true, 'Password hash is required'],
  },
  createdAt: {
    type: Date,
    default: Date.now,
    immutable: true,    // never allow createdAt to be overwritten on update
  },
});

const User = mongoose.model('User', userSchema);

export default User;
